version: '3'
services:
  postgres:
    container_name: sample-db
    image: postgres:latest
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - 8085:8080
    depends_on:
      - postgres

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"