spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://localhost:5432/dev
  username: postgres
  password: postgres
  platform: postgres
  driver-class-name: org.postgresql.Driver

  spring.jpa:
    database: postgresql
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true
    show-sql: true